# Generated by Django 2.2.5 on 2020-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('develop', 'Under Development'), ('testing', 'Under Testing'), ('publish', 'Published')], default='develop', max_length=8),
        ),
    ]
