# Generated by Django 2.2.5 on 2020-07-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_auto_20200524_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('develop', 'Under Development'), ('staging', 'Under Testing'), ('publish', 'Published')], default='develop', max_length=8),
        ),
    ]
