# Generated by Django 2.2.5 on 2020-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_auto_20200714_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('develop', 'Under Development'), ('staging', 'Under Staging'), ('publish', 'Published')], default='develop', max_length=8),
        ),
    ]
