# Generated by Django 2.2.5 on 2020-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('playable', 'Playable'), ('tutorial', 'Tutorial'), ('plugin', 'Plugin')], default='playable', max_length=16),
        ),
    ]
