# Generated by Django 2.2.5 on 2020-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
